import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'About'
}

export default function AboutPage() {
  return (
      <>
        <h2 className="text-xl font-medium mt-6 border-b border-black phone:w-7/12 phone:text-lg">Origin Story of Japanese pro wrestling &#40;<i>puroresu</i>&#41;</h2>
        <p className="w-7/12 pt-6 pb-2"> 
          Let&apos;s talk about the enduring legacy of Japanese professional wrestling, commonly known as <i>puroresu</i>, which has spanned over half a century. It traces its origins back to the early 1950s when Rikid&#333;zan made his debut as a pro wrestler after retiring from sumo wrestling. In the aftermath of Japan&apos;s defeat in World War II, Rikid&#333;zan emerged as a courageous figure willing to stand up against the Americans.
        </p>
        <p className="w-7/12 py-2">
          Rikid&#333;zan established Japan&apos;s first wrestling promotion, Japan Pro Wrestling Alliance &#40;JWA&#41;, and its initial shows garnered tremendous popularity with thousands of fans in attendance. The former sumo wrestler achieved great stardom and became a beloved local hero for Japanese fans as he triumphed over American wrestlers who portrayed antagonistic roles. Notably, in 1958, he defeated Lou Thesz to capture the NWA International Heavyweight Championship. Rikid&#333;zan&apos;s immense popularity as a national wrestling star and hero earned him the moniker <strong>The Father of Puroresu</strong> and played a pivotal role in popularizing professional wrestling in Japan.
        </p>
        <p className="w-7/12 py-2">
          Unfortunately, puroresu took a tragic turn when Rikid&#333;zan was murdered in 1963 by a yakuza member. Following his untimely demise, Japan Pro Wrestling Alliance continued to operate as the country&apos;s premier wrestling circuit throughout the late 1960s but faced difficulties in the early 1970s. Its top stars, Giant Baba and Antonio Inoki, left JWA to establish All Japan Pro Wrestling &#40;AJPW&#41; and New Japan Pro Wrestling &#40;NJPW&#41;, respectively, in 1972. This led to the disbandment of JWA the following year.
        </p>
        <p className="w-7/12 py-2">
          During the 1970s and 1980s, puroresu underwent significant evolution and continued to thrive. Inoki collaborated with catch wrestling veteran Karl Gotch in NJPW, blending Inoki&apos;s martial arts background and Rikid&#333;zan&apos;s hard-hitting style with Gotch&apos;s technical expertise and catch wrestling skills. This fusion gave rise to Strong Style, a style of wrestling that revolutionized Japanese pro wrestling. In 1976, Inoki faced off against world boxing champion Muhammad Ali in a highly anticipated event dubbed &quot;The War of the Worlds&quot;, which ended in a draw and elevated Inoki to international wrestling stardom. Inoki utilized strong style wrestling to compete against champions from various martial arts disciplines, including Ali, to assert the dominance of pro wrestling as a fighting discipline. Both NJPW and AJPW endeavored to shed light on Japanese wrestling by bringing in foreign stars to compete against Japanese wrestlers, notably through tournaments like NJPW&apos;s G1 Climax and AJPW&apos;s Champion Carnival. Foreign wrestlers who competed in Japan were referred to as <i>gaijins</i>. NJPW showcased talents such as Hulk Hogan, Andr&#233; the Giant, Stan Stasiak, and Pedro Morales, while AJPW featured Stan Hansen, Dory Funk Jr., Terry Funk, Mil Mascaras, and Abdullah the Butcher.
        </p>
        <p className="w-7/12 py-2">
          In the late 1980s, major world championships were introduced in Japanese wrestling. In NJPW, the official IWGP Heavyweight Championship was established in 1987 and held prominence until 2021. However, four years prior to its introduction, an early version of the heavyweight title was established, and Hulk Hogan became its inaugural champion. In addition, Inoki held the title twice before it was deactivated and replaced by the official heavyweight title, which was awarded to the winner of the IWGP League in 1987, making Inoki the first-ever IWGP Heavyweight Champion. In AJPW, before the creation of the Triple Crown Heavyweight Championship in 1989, a winner-takes-all match took place. Jumbo Tsuruta held the NWA International Heavyweight Championship, one of the titles previously held by Rikid&#333;zan, while Stan Hansen simultaneously held the PWF Heavyweight Championship and the NWA United National Championship. They competed in a unification match, with Tsuruta emerging victorious to become the inaugural Triple Crown Heavyweight Champion.
        </p>
        <p className="w-7/12 py-2">
          The NJPW and AJPW world championships quickly gained prestige in their early years, with a mix of Japanese and gaijin champions, including Big Van Vader, Stan Hansen, Steve Williams, Salman Hashimikov, and Scott Norton. These champions and wrestlers played a crucial role in upholding the legacy of professional wrestling, showcasing their impressive skills and captivating performances in the ring. For instance, Stan Hansen, a four-time Triple Crown Heavyweight Champion, was renowned for his exceptional strength and endurance, which he employed to devastating effect with his signature arm strike finisher, the Lariat. Champions and wrestlers who received significant pushes were expected to deliver outstanding in-ring displays, particularly on television, without exposing any flaws.
        </p>
        <p className="w-7/12 py-2">
          After the passing of Giant Baba in 1999, AJPW top star Mitsuharu Misawa assumed the position of company president, while Baba&apos;s wife, Motoko, oversaw the promotion&apos;s operations. However, disagreements arose between Misawa and Motoko, leading Misawa to depart from the promotion along with many All Japan roster members, including Kenta Kobashi, Jun Akiyama, and Akira Taue, to establish Pro Wrestling Noah. Others like Toshiaki Kawada and Masanobu Fuchi opted to stay with All Japan to fulfill Baba&apos;s final wish of keeping the promotion alive. Misawa stated that Pro Wrestling Noah was formed to showcase a more contemporary style of wrestling. Subsequently, a new world championship, the GHC Heavyweight Championship, was established in Pro Wrestling Noah, with Misawa becoming its inaugural champion, utilizing the wrestling expertise he had developed during his time in AJPW.
        </p>
        <p className="w-7/12 py-2">
          Lastly, as previously mentioned, the IWGP Heavyweight Championship remained active from 1987 to 2021. Following its discontinuation, Kota Ibushi defeated El Desperado to unify the IWGP Heavyweight and Intercontinental Championships, creating the IWGP World Heavyweight Championship and becoming its inaugural titleholder. This new world championship became NJPW&apos;s new top title.
        </p>
        <p className="w-7/12 pt-2 pb-6">
          Puroresu has continued to grow and evolve throughout the decades and generations, particularly within major Japanese promotions. Three distinct world championships were established to carry on the legacy of Japanese wrestling. The IWGP championship symbolizes strong style wrestling due to Inoki&apos;s pioneering efforts and his status as the first IWGP Heavyweight Champion. The AJPW championship represents the legacy of Rikid&#333;zan, who held the NWA International Championship, one of the titles unified to form All Japan&apos;s top title. Lastly, the GHC championship embodies modern style wrestling, developed by Misawa during his tenure in AJPW, with Misawa himself becoming the inaugural champion. Analyzing the list of world champions within these three major Japanese promotions will shed light on the wrestlers who truly embody the essence of puroresu.
        </p>
      </>
  )
}